spring.application.name=FoodDeliverySystem
server.port = 8081


spring.profiles.active=${ENV:dev}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=false

